### ISSUE TITLE
代码中的评价指标问题。

### ISSUE THREAD

**Issue by YuQi9797** [chaneyddtt/UDA-Animal-Pose#13]
您好，请问
https://github.com/chaneyddtt/UDA-Animal-Pose/blob/f1ebfda860a2585c60fe86ce1632e910ac97ebc5/evaluation/test.py#L190
此处`acces.avg`  是否就是 论文中PCK@0.05 中的Mean 呢？ 而` print('\n Joint {}: {} '.format(p, score/count))` 即为对应每个部位的结果？

**Comment by chaneyddtt** [comment]
您好，您的理解是正确的。

**Comment by YuQi9797** [comment]
奥，谢谢您！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Li ***@***.***&gt;; 
发送时间: 2022年1月4日(星期二) 下午4:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chaneyddtt/UDA-Animal-Pose] 代码中的评价指标问题。 (Issue #13)





 
您好，您的理解是正确的。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
