### ISSUE TITLE
Confusion about get_cropped_TigDog.py

### ISSUE THREAD

**Issue by davidpengiupui** [chaneyddtt/UDA-Animal-Pose#14]
Thank you so much for your code and work! I've got a question about the get_cropped_TigDog.py and really need your help. In line 108-124 you rescale the images to 1.25 and then save them, but I didn't see the corresponding adjustments to the annotations and where these annotations are saved. Could you please give me some instructions?

**Comment by chaneyddtt** [comment]
Hi @davidpengiupui, we do not need to adjust the annotations because we do not use the ground truth keypoints during training. During testing, the keypoints are adjust accordingly using the 'c' and 's'  in the real_animal_all.py

**Comment by davidpengiupui** [comment]
Thank you for your explanation!
