### ISSUE TITLE
GPUs requirement and training time

### ISSUE THREAD

**Issue by dongfengxijian** [chaneyddtt/UDA-Animal-Pose#5]
If I want to train this network， how many GPUs and how long  I need? Thanks！

**Comment by chaneyddtt** [comment]
Hi @dongfengxijian, I train the network with one RTX2080Ti GPU, so one gpu with 12G memory should be enough.

**Comment by dongfengxijian** [comment]
> Hi @dongfengxijian, I train the network with one RTX2080Ti GPU, so one gpu with 12G memory should be enough.

Thank you for your replying.
