### ISSUE TITLE
Does anyone know where the code for metric PCK@0.05 ?

### ISSUE THREAD

**Issue by YuQi9797** [chaneyddtt/UDA-Animal-Pose#6]
I see the code in https://github.com/chaneyddtt/UDA-Animal-Pose/blob/f1ebfda860/evaluation/test.py#L140 ,  there are not threshold about 0.05. and the `pck_score[j] += acc[j + 1].numpy()`   calculates acc instead of PCK ?

Can someone tell me where I'm going wrong?

**Comment by chaneyddtt** [comment]
Hi @YuQi9797, please refer to the accuracy_2animal() for more details. Basically, the distance is firstly normalized by 'output.size(3)/10' and them compared to a threshold 0.5. That is how the 0.05 comes from. We adopt this evaluation metric from [previous work](https://github.com/JitengMu/Learning-from-Synthetic-Animals). Hope this clarifies.

**Comment by YuQi9797** [comment]
Sir,&nbsp;Is there no difference between accuracy_2animal () and accuracy ()?&nbsp;


The only difference is that the accuray () is used to train and calculate the 19 key points, while the accuracy_aAnimal () is used to calculate the 18 key points. But essentially there is no difference between the two functions.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chaneyddtt/UDA-Animal-Pose"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月13日(星期二) 晚上9:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chaneyddtt/UDA-Animal-Pose] Does anyone know where the code for metric ***@***.*** ? (#6)





 
Hi @YuQi9797, please refer to the accuracy_2animal() for more details. Basically, the distance is firstly normalized by 'output.size(3)/10' and them compared to a threshold 0.5. That is how the 0.05 comes from. We adopt this evaluation metric from previous work. Hope this clarifies.

**Comment by YuQi9797** [comment]
Sir, Is there no difference between accuracy_2animal () and accuracy ()?

The only difference is that the accuray () is used to train and calculate the 19 key points, while the accuracy_animal () is used to calculate the 18 key points. But essentially there is no difference between the two functions.
