### ISSUE TITLE
PCK@0.05?

### ISSUE THREAD

**Issue by wangkaihong** [chaneyddtt/UDA-Animal-Pose#8]
Hi! 

Thanks for the remarkable work! Just wanted to check if the PCK@0.05 is actually PCK@0.5, as shown in:

https://github.com/chaneyddtt/UDA-Animal-Pose/blob/f1ebfda860a2585c60fe86ce1632e910ac97ebc5/pose/utils/evaluation.py#L183

where the threshold is set by default as 0.5?

**Comment by wangkaihong** [comment]
Just found the explanation in another issue, sorry for the repeated question!

**Comment by YuQi9797** [comment]
> 你好！
> 
> 感谢出色的工作！只是想检查一下PCK@0.05是否真的是PCK@0.5，如图：
> 
> https://github.com/chaneyddtt/UDA-Animal-Pose/blob/f1ebfda860a2585c60fe86ce1632e910ac97ebc5/pose/utils/evaluation.py#L183
> 
> 阈值默认设置为0.5？

您好，请问这里的pck到底是0.5 还是 0.05呢？

**Comment by chaneyddtt** [comment]
Hi, please note that the dist is firstly normalized as:
![image](https://user-images.githubusercontent.com/31334319/157851198-0aa2a6d3-ce91-4dbf-a45e-79aa0304c0f4.png)
and the 'normalize' here is output_size/10.
