### ISSUE TITLE
Number of stage

### ISSUE THREAD

**Issue by wangkaihong** [chaneyddtt/UDA-Animal-Pose#9]
Hi,

I notice that the pretrained model is under a folder named "stage2", does that mean the model is trained with 2 iterations of pseudo-label generation and self-training?

Thanks

**Comment by chaneyddtt** [comment]
Hi, the model pretrained using synthetic data is under 'stage1', and the model under 'stage2' is our released model for testing. We conducted one iteration of pseudo-label training in our paper.

**Comment by wangkaihong** [comment]
I see, thanks for the clarification!
